### ISSUE TITLE
[BUG] Does not run under linux

### ISSUE THREAD

**Issue by tbellembois** [GPh83/resticterm#12]
**Describe the bug**
Does not run under Linux. Tested with Manjaro.

**To Reproduce**
```bash
./resticterm.exe                                                                                                                                                                            ✔ 
Cannot open assembly './resticterm.exe': File does not contain a valid CIL image.
```

**Expected behavior**
Run the GUI.

**Context (please complete the following information):**
 - OS: Manjaro
 - Version: 5.15.28-1 64 bits

**Comment by GPh83** [comment]
Have you make it executable ?

With command line :
`chmod u+x ./resticterm.exe`

Which architecture is your processor  ?

Thanks

**Comment by tbellembois** [comment]
Yes I have chmod it.
I have a 64bits `Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz` processor.

**Comment by GPh83** [comment]
It s ok with Ubuntu but not with Manjaro.
It s seems the package with .net5 doesn't work on Manjaro.
I will try other package type for Manjaro.
I ll give you feedback later.

**Comment by colans** [comment]
@GPh83 Would love to get this working on Linux, but I get:

```bash
% cat /etc/issue                                                                                               
Pop!_OS 22.04 LTS [An Ubuntu fork]

% ./resticterm.exe                                                                                             
run-detectors: unable to find an interpreter for ./resticterm.exe
```

Is there something I'm missing if this is supposed to run in Ubuntu?

How much would it cost for you to get this working?

**Comment by GPh83** [comment]
It's deployment problem. Working on some distib but not all.

**Comment by GPh83** [comment]
Normaly solved. (Ok for Ubuntu, doesn't test on other distrib)
Try : https://github.com/GPh83/resticterm/releases/download/V0.9.0.0/resticterm_Linux_x64_V0.9.0.0.zip

**Comment by colans** [comment]
Thanks!  It starts up now.  There are other problems, but I'll open these as other tickets.
