### ISSUE TITLE
[BUG] Fatal: wrong password or no key found

### ISSUE THREAD

**Issue by PnYMaT** [GPh83/resticterm#15]
**Describe the bug**
If a repository is created directly with restic.exe with password "toto", password "toto" will not work if you use repository in Resticterm. And in the same way if a repository is created directly with Resticterm with password "toto", password "toto" will not work if you use repository directly with restic.exe

**To Reproduce**
Create an use a repository with password "toto" with Resticterm, with path "c:\resticterm_repo"
Now, try to use it with restic.exe
set RESTIC_PASSWORD=toto
restic.exe --repo "c:\resticterm_repo" backup --verbose c:\files_to_backup

**Expected behavior**
Restic repository must work with the same password if created by restic.exe directly or with Resticterm

**Screenshots**
No screen shots

**Context (please complete the following information):**
 - OS: Windows 10

**Additional context**
Thanks for your help

**Comment by GPh83** [comment]
Sorry but It's working !

Probably environnement variable issue.
If you are using powershell you need to set environnement variable like this : `Set-Item -Path Env:RESTIC_PASSWORD -Value ("toto")`
Check : `Get-Childitem -path env: `

**Comment by PnYMaT** [comment]
Hi,

Ok, i will do more test.
