### ISSUE TITLE
[REQ] Add support for remote Rclone repositories over SSH

### ISSUE THREAD

**Issue by colans** [GPh83/resticterm#16]
**Is your feature request related to a problem? Please describe.**

Normally I run Restic like this:

* `/usr/bin/restic --option rclone.program="ssh username@backups.example.com rclone" --option rclone.args="serve restic --stdio --b2-hard-delete --drive-use-trash=false --verbose" --repo rclone:remote-storage:backupservice-prod-ca-ymq-1-snapshots-colan --password-file /etc/restic/password --verbose ${@}`

The Restic documentation for this is at [Other Services via rclone](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone).

However, on the configuration page, there's only an option to enter the repository path, which doesn't capture all of the above.

**Describe the solution you'd like**

Ideally, it would be possible to enter this information on the CLI when running `resticterm` the same way, like so:

* `/opt/resticterm/resticterm --option rclone.program="ssh username@backups.example.com rclone" --option rclone.args="serve restic --stdio --b2-hard-delete --drive-use-trash=false --verbose" --repo rclone:remote-storage:backupservice-prod-ca-ymq-1-snapshots-colan --password-file /etc/restic/password --verbose ${@}`

Failing that, it should be possible to enter this additional information on the configuration form.

**Describe alternatives you've considered**

Restic Browser, but it [has the same problem](https://github.com/emuell/restic-browser/issues/56).  And ever worse, it doesn't work in a terminal.

**Additional context**

I'm on recent Ubuntu.

**Comment by GPh83** [comment]
The goal of _resticterm_ is to have a simply console user interface to remove command line use.
It is not intented for replace all _restic_ functionalities. You can continue to use command line for advanced use.

I take into account the possibility of adding extra parameters in setup form.

**Comment by colans** [comment]
If I were to pay you, how much would it cost for you to add this feature?
