### ISSUE TITLE
[REQ] Allow configuration from CLI options or document location of configuration file on Linux

### ISSUE THREAD

**Issue by colans** [GPh83/resticterm#17]
**Is your feature request related to a problem? Please describe.**

I can't seem to enter configuration information when running the command.  This doesn't work:

* `/opt/resticterm/resticterm --help`
* `/opt/resticterm/resticterm --repository-path="/path/to/repo"`
* `/opt/resticterm/resticterm --password="supersecret"`

And I can't find the configuration file on Ubuntu.  So I'm forced to enter the information on the configuration form.

**Describe the solution you'd like**

I need to be able to script the configuration.  So either:
1. Allow command-line options for configuration, or
2. Tell me where to find the configuration file in Linux/Ubuntu, and I can write that file first, and then run `resticterm`.  This location should be documented.

**Describe alternatives you've considered**

https://github.com/emuell/restic-browser, but it doesn't work in a terminal.

**Additional context**

Ubuntu Linux.

**Comment by GPh83** [comment]
1. The goal of _resticterm_ is to remove command line usage ...
2. The configuration file is in the current folder of _recticterm_. Filename : _recticterm.config.json_

_help_ option is a good improvement.
An option for specifying the config file location is also interesting.

**Comment by GPh83** [comment]
The extra parameter in setup can (probably) resolve you need.
