### ISSUE TITLE
[REQ] Rclone support

### ISSUE THREAD

**Issue by 1024mb** [GPh83/resticterm#9]
Would be awesome if rclone support could be added, currently pointing to the repo with `rclone:Remote:Path` doesn't work.

**Comment by GPh83** [comment]
Update V0.7.1 is now Ok for all type of repo.

**Comment by 1024mb** [comment]
Thanks.
I tried adding my rclone repo and got this exception:

```
Se produjo una excepción excepción inesperada del programa (0xe0434352) en la aplicación en la ubicación 0x00007FFED27E4F69.
```

Also, I already had a config file with the RepoPath value set to the rclone repository (the app did saved that the previous run) but when I tried launching resticterm it crashed at "Summary in progress..." so I had to rename it.

**Comment by GPh83** [comment]
I  nerver use clone but i need to try it for debug this :)
